### PR TITLE
Second request - Brochure updated. 

### PR DESCRIPTION
**Pull request by psd-nurseha**
Thanks for your help!

### CODE REVIEW

**Comment by psd-nurseha** [comment]
To proceed

**Review by psd-nurseha — COMMENTED** [review]
Ok

**Review by psd-nurseha — COMMENTED** [review]
Ok

**Review by psd-nurseha — COMMENTED** [review]
Ok

**Review by psd-nurseha — COMMENTED** [review]
Ok

**Review by psd-nurseha — COMMENTED** [review]
Ok

**Review by psd-nurseha — COMMENTED** [review]
Ok

**Review by psd-nurseha — COMMENTED** [review]
All ok

**Review by psd-nurseha — COMMENTED** [review]
Go ahead

**Review by PSD-Wailee — APPROVED** [review]
ok.

**Review by PSD-Wailee — APPROVED** [review]
ok..

**Review by psdsamantha — APPROVED** [review]

**Review by psdsamantha — APPROVED** [review]
Ok

**Pull request merged**
