### PR TITLE
Update 2021-virtual-information-session.md

### PR DESCRIPTION
**Pull request by PSD-Wailee**
Brenda, pls approve.

### CODE REVIEW

**Review by brendasee — APPROVED** [review]

**Review by brendasee — APPROVED** [review]

**Review by brendasee — APPROVED** [review]

**Review by brendasee — APPROVED** [review]

**Review by brendasee — APPROVED** [review]

**Review by brendasee — APPROVED** [review]

**Review by brendasee — APPROVED** [review]

**Review by brendasee — COMMENTED** [review]
appv

**Review by brendasee — APPROVED** [review]

**Comment by brendasee** [comment]
approved

**Review by brendasee — APPROVED** [review]
appv

**Comment by PSD-Wailee** [comment]
thanks

**Review by PSD-Wailee — COMMENTED** [review]
thanks

**Review by brendasee — APPROVED** [review]
kk

**Review by brendasee — APPROVED** [review]

**Review by brendasee — COMMENTED** [review]
ok

**Pull request closed without merging**
